### ISSUE TITLE
Rollup 2 support

### ISSUE THREAD

**Issue by eshimischi** [MikeKovarik/gulp-better-rollup#45] opened 2020-04-12 08:29 UTC
Any plans on updating your library to Rollup 2 ?

**Comment by duzun** [comment] 2021-01-06 10:59
I'm using rollup@2 with this lib for a while now and it works great.
Related #48

**Comment by Honatas** [comment] 2021-03-19 20:02
This gulp plugin works 100% with version 2 of Rollup. The problem is, with npm version 7 the build is breaking:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: myproject@1.0.0
npm ERR! Found: rollup@1.32.1
npm ERR! node_modules/rollup
npm ERR!   dev rollup@"^1.32.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer rollup@"^2.14.0" from @rollup/plugin-typescript@6.1.0
npm ERR! node_modules/@rollup/plugin-typescript
npm ERR!   dev @rollup/plugin-typescript@"^6.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

@duzun 's #48 pull request fixes this problem.

@MikeKovarik can you please accept the PR? Or else we'll have to either keep using the --legacy-peer-deps flag or revert to using npm 6.

**Comment by Zardoz89** [comment] 2021-06-10 07:32
> I'm using rollup@2 with this lib for a while now and it works great.
> Related #48

Not so great, some options doesn't work : 

```
Unknown output options: external. Allowed options: amd, assetFileNames, banner, chunkFileNames, compact, dir, dynamicImportFunction, entryFileNames, esModule, exports, extend, externalLiveBindings, file, footer, format, freeze, globals, hoistTransitiveImports, indent, inlineDynamicImports, interop, intro, manualChunks, minifyInternalExports, name, namespaceToStringTag, noConflict, outro, paths, plugins, preferConst, preserveModules, preserveModulesRoot, sanitizeFileName, sourcemap, sourcemapExcludeSources, sourcemapFile, sourcemapPathTransform, strict, systemNullSetters, validate
```

```
    .pipe(
      rollup(
        {
          plugins: [babel.babel(config.babel)],
        },
        {
          format: "iife",
          globals: {
            jquery: "$",
            moment: "moment",
            clipboard: "ClipboardJS",
            openseadragon: "OpenSeadragon",
          },
          external: ["jquery", "moment", "clipboard", "OpenSeadragon"],
        }
      )
    )
```

**Comment by massadm** [comment] 2023-02-19 11:39
As of npm cli [v8.3.0](https://github.com/npm/cli/releases/tag/v8.3.0) (2021-12-09) this can be solved using the [overrides field](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) of your package.json.

```json
"overrides": {
  "gulp-better-rollup": {
    "rollup": "^1||^2||^3"
  }
}
```

**Closed as completed** 2023-02-19 17:16 UTC

**Comment by Zardoz89** [comment] 2023-02-20 05:58
@massadm Try to use https://github.com/tborychowski/gulp-rollup-plugin as it's a updated and maintained fork, instead using workaround with a gulp plugin that has been updated in years.
